# Generated by Django 3.2.6 on 2021-10-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_despues', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Producto/%y/m/%d')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.producto2')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ['id'],
            },
        ),
    ]
