# Generated by Django 3.2.6 on 2021-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emergencia', models.CharField(max_length=200, unique=True, verbose_name='Emergencia')),
                ('Advertencia', models.CharField(max_length=200, unique=True, verbose_name='Advertencia')),
                ('Aviso', models.CharField(max_length=200, unique=True, verbose_name='Aviso')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['id'],
            },
        ),
    ]
