# Generated by Django 3.2.6 on 2021-09-22 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombreuser', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('Mensaje', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Imagen/%y/m/%d')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Avatar/%y/m/%d')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'ordering': ['id'],
            },
        ),
    ]
