# Generated by Django 3.2.6 on 2021-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
    ]
