# Generated by Django 3.2.6 on 2021-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, unique=True, verbose_name='Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen/%y/m/%d')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
