# Generated by Django 3.2.6 on 2021-10-11 23:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Cargo')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creacion')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Estado')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombres')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de ingreso')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('Cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.cargos')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.estado')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
                'ordering': ['id'],
            },
        ),
    ]
