# Generated by Django 3.2.6 on 2021-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.CharField(max_length=300, verbose_name='Mensaje')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Avatar/%y/m/%d')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Imagen/%y/m/%d')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['id'],
            },
        ),
    ]
