# Generated by Django 3.2.6 on 2021-10-05 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_ventas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Ventas',
        ),
        migrations.AddField(
            model_name='ventas',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ventas',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
