# Generated by Django 3.2.6 on 2021-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Avatar/%y/m/%d')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['id'],
            },
        ),
    ]
