# Generated by Django 3.2.6 on 2021-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('Educacion', models.CharField(max_length=100, verbose_name='Educacion')),
                ('Habilidades', models.CharField(max_length=200, verbose_name='Habilidades')),
                ('Notas', models.CharField(max_length=200, verbose_name='Notas')),
                ('Localizacion', models.CharField(max_length=100, verbose_name='Localizacion')),
                ('Correo', models.CharField(max_length=150, verbose_name='Correo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Categoria/%y/m/%d')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['id'],
            },
        ),
    ]
