# Generated by Django 3.2.6 on 2021-10-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_alter_perfil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
