# Generated by Django 3.2.6 on 2021-10-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto2',
            old_name='Categoria',
            new_name='category',
        ),
    ]
