# Generated by Django 3.2.6 on 2021-10-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0002_producto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto2',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categorias.categorias'),
        ),
    ]
